language: php

php:
    - 7.1.13
    - 7.2
env:
    matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install --dev
  - composer update $PREFER_LOWEST

script: ./vendor/bin/phpunit
