language: php

php:
    - 5.3
    - 5.6

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - rm composer.lock
  - composer install --dev
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update && composer update --dev; fi;

script: phpunit

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.3
      env: SYMFONY_VERSION=2.8.*
      dist: precise
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
    - php: 5.6
      env: SYMFONY_VERSION=3.1.*
  exclude:
    - php: 5.3
