language: php

php:
    - 5.6
    - 7.0

before_script:
  - composer self-update
  - composer install --dev
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update && composer update --dev; fi;

script: phpunit

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
    - php: 7
      env: SYMFONY_VERSION=3.0.*
    - php: 7
      env: SYMFONY_VERSION=dev-master@dev
  allow_failures:
    - env: SYMFONY_VERSION=dev-master@dev
