language: php

php:
    - 7.1.13
    - 7.2

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install --dev

script: ./vendor/bin/phpunit

matrix:
  include:
    - php: 7.2
      env: SYMFONY_VERSION=3.0.*
    - php: 7.2
      env: SYMFONY_VERSION=^3
    - php: 7.2
      env: SYMFONY_VERSION=^4
    - php: 7.2
      env: SYMFONY_VERSION=dev-master@dev
  allow_failures:
    - env: SYMFONY_VERSION=dev-master@dev
